const axios = require("axios");
const { channelCard } = require("../utils/functions");

// ============================================================
// AI commands — powered by pollinations.ai (100% free, no key)
// ============================================================

const aiCommands = {
  ai: {
    description: "Chat with AI",
    usage: ".ai <your message>",
    category: "AI",
    handler: async ({ sock, msg, jid, args }) => {
      const prompt = args.join(" ");
      if (!prompt)
        return sock.sendMessage(jid, { text: "Usage: .ai <your message>" }, { quoted: msg });

      await sock.sendMessage(jid, { text: "🤖 Thinking..." }, { quoted: msg });

      try {
        const res = await axios.post(
          "https://text.pollinations.ai/",
          {
            messages: [
              { role: "system", content: "You are a helpful assistant. Keep replies concise and friendly." },
              { role: "user", content: prompt },
            ],
            model: "openai",
            private: true,
          },
          { timeout: 30000, headers: { "Content-Type": "application/json" } }
        );

        const reply =
          typeof res.data === "string"
            ? res.data
            : res.data?.choices?.[0]?.message?.content ?? "No response.";

        await sock.sendMessage(
          jid,
          { text: `🤖 *AI:*\n\n${reply.trim()}` },
          { quoted: channelCard() }
        );
      } catch {
        await sock.sendMessage(
          jid,
          { text: "❌ AI is temporarily unavailable. Try again in a moment." },
          { quoted: msg }
        );
      }
    },
  },

  imagine: {
    description: "Generate an AI image from a text prompt",
    usage: ".imagine <description>",
    category: "AI",
    handler: async ({ sock, msg, jid, args }) => {
      const prompt = args.join(" ");
      if (!prompt)
        return sock.sendMessage(jid, { text: "Usage: .imagine <description of the image>" }, { quoted: msg });

      await sock.sendMessage(jid, { text: "🎨 Generating image..." }, { quoted: msg });

      try {
        const encoded = encodeURIComponent(prompt);
        const url = `https://image.pollinations.ai/prompt/${encoded}?width=768&height=768&nologo=true&enhance=true`;

        const imageRes = await axios.get(url, { responseType: "arraybuffer", timeout: 60000 });
        const buffer = Buffer.from(imageRes.data);

        await sock.sendMessage(
          jid,
          { image: buffer, caption: `🎨 *"${prompt}"*\n\n_Generated by AI_` },
          { quoted: channelCard() }
        );
      } catch {
        await sock.sendMessage(
          jid,
          { text: "❌ Image generation failed. Try a different prompt." },
          { quoted: msg }
        );
      }
    },
  },
};

module.exports = { aiCommands };
